// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: oop.proto

package oop

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//when insert or update one ops, this struct will return the result and the ops which is be inserted
type OneResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Data *Oop   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OneResult) Reset() {
	*x = OneResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneResult) ProtoMessage() {}

func (x *OneResult) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneResult.ProtoReflect.Descriptor instead.
func (*OneResult) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{0}
}

func (x *OneResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OneResult) GetData() *Oop {
	if x != nil {
		return x.Data
	}
	return nil
}

type Oop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid          string        `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Uid          string        `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content      string        `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime   string        `protobuf:"bytes,4,opt,name=create_time,proto3" json:"create_time,omitempty"`
	ShardTimes   int32         `protobuf:"varint,5,opt,name=shard_times,proto3" json:"shard_times,omitempty"`
	CommentTimes int32         `protobuf:"varint,6,opt,name=comment_times,proto3" json:"comment_times,omitempty"`
	LikeTimes    int32         `protobuf:"varint,7,opt,name=like_times,proto3" json:"like_times,omitempty"`
	IsPrivate    bool          `protobuf:"varint,8,opt,name=is_private,proto3" json:"is_private,omitempty"`
	LikeDetail   []*LikeDetail `protobuf:"bytes,9,rep,name=like_detail,proto3" json:"like_detail,omitempty"`
	MyLikeInfo   *LikeDetail   `protobuf:"bytes,10,opt,name=my_like_info,proto3" json:"my_like_info,omitempty"`
	AtUsers      string        `protobuf:"bytes,11,opt,name=at_users,proto3" json:"at_users,omitempty"`
}

func (x *Oop) Reset() {
	*x = Oop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oop) ProtoMessage() {}

func (x *Oop) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oop.ProtoReflect.Descriptor instead.
func (*Oop) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{1}
}

func (x *Oop) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *Oop) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Oop) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Oop) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Oop) GetShardTimes() int32 {
	if x != nil {
		return x.ShardTimes
	}
	return 0
}

func (x *Oop) GetCommentTimes() int32 {
	if x != nil {
		return x.CommentTimes
	}
	return 0
}

func (x *Oop) GetLikeTimes() int32 {
	if x != nil {
		return x.LikeTimes
	}
	return 0
}

func (x *Oop) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Oop) GetLikeDetail() []*LikeDetail {
	if x != nil {
		return x.LikeDetail
	}
	return nil
}

func (x *Oop) GetMyLikeInfo() *LikeDetail {
	if x != nil {
		return x.MyLikeInfo
	}
	return nil
}

func (x *Oop) GetAtUsers() string {
	if x != nil {
		return x.AtUsers
	}
	return ""
}

type DeleteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid string `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Delete) Reset() {
	*x = Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{3}
}

func (x *Delete) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *Delete) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

//this struct will return all of the oop of single user
type ManyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ShowNumber  int64  `protobuf:"varint,2,opt,name=show_number,proto3" json:"show_number,omitempty"`
	CurrentPage int64  `protobuf:"varint,3,opt,name=current_page,proto3" json:"current_page,omitempty"`
	Timestamp   string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data        []*Oop `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ManyResult) Reset() {
	*x = ManyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManyResult) ProtoMessage() {}

func (x *ManyResult) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManyResult.ProtoReflect.Descriptor instead.
func (*ManyResult) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{4}
}

func (x *ManyResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ManyResult) GetShowNumber() int64 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

func (x *ManyResult) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ManyResult) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ManyResult) GetData() []*Oop {
	if x != nil {
		return x.Data
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Timestamp  string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ShowNumber int64  `protobuf:"varint,3,opt,name=show_number,proto3" json:"show_number,omitempty"`
	PageNumber int64  `protobuf:"varint,4,opt,name=page_number,proto3" json:"page_number,omitempty"`
	SelfUid    string `protobuf:"bytes,5,opt,name=self_uid,proto3" json:"self_uid,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{5}
}

func (x *Query) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Query) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Query) GetShowNumber() int64 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

func (x *Query) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *Query) GetSelfUid() string {
	if x != nil {
		return x.SelfUid
	}
	return ""
}

type FollowOop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        []string `protobuf:"bytes,1,rep,name=uid,proto3" json:"uid,omitempty"`
	Timestamp  string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ShowNumber int64    `protobuf:"varint,3,opt,name=show_number,proto3" json:"show_number,omitempty"`
	PageNumber int64    `protobuf:"varint,4,opt,name=page_number,proto3" json:"page_number,omitempty"`
	SelfUid    string   `protobuf:"bytes,5,opt,name=self_uid,proto3" json:"self_uid,omitempty"`
}

func (x *FollowOop) Reset() {
	*x = FollowOop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowOop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowOop) ProtoMessage() {}

func (x *FollowOop) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowOop.ProtoReflect.Descriptor instead.
func (*FollowOop) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{6}
}

func (x *FollowOop) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *FollowOop) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FollowOop) GetShowNumber() int64 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

func (x *FollowOop) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *FollowOop) GetSelfUid() string {
	if x != nil {
		return x.SelfUid
	}
	return ""
}

type Like struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Oid        string `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`
	Star       int64  `protobuf:"varint,3,opt,name=star,proto3" json:"star,omitempty"`
	CreateTime string `protobuf:"bytes,4,opt,name=create_time,proto3" json:"create_time,omitempty"`
}

func (x *Like) Reset() {
	*x = Like{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{7}
}

func (x *Like) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Like) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *Like) GetStar() int64 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Like) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type LikeOopResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LikeOopResult) Reset() {
	*x = LikeOopResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeOopResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeOopResult) ProtoMessage() {}

func (x *LikeOopResult) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeOopResult.ProtoReflect.Descriptor instead.
func (*LikeOopResult) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{8}
}

func (x *LikeOopResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CancelLike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Oid string `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`
}

func (x *CancelLike) Reset() {
	*x = CancelLike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLike) ProtoMessage() {}

func (x *CancelLike) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLike.ProtoReflect.Descriptor instead.
func (*CancelLike) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{9}
}

func (x *CancelLike) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CancelLike) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

type CancelLikeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CancelLikeResult) Reset() {
	*x = CancelLikeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelLikeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLikeResult) ProtoMessage() {}

func (x *CancelLikeResult) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLikeResult.ProtoReflect.Descriptor instead.
func (*CancelLikeResult) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{10}
}

func (x *CancelLikeResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type MyLike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ShowNumber int64  `protobuf:"varint,2,opt,name=show_number,proto3" json:"show_number,omitempty"`
	PageNumber int64  `protobuf:"varint,3,opt,name=page_number,proto3" json:"page_number,omitempty"`
}

func (x *MyLike) Reset() {
	*x = MyLike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyLike) ProtoMessage() {}

func (x *MyLike) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyLike.ProtoReflect.Descriptor instead.
func (*MyLike) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{11}
}

func (x *MyLike) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MyLike) GetShowNumber() int64 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

func (x *MyLike) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type MyLikeOopResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ShowNumber  int64  `protobuf:"varint,2,opt,name=show_number,proto3" json:"show_number,omitempty"`
	CurrentPage int64  `protobuf:"varint,3,opt,name=current_page,proto3" json:"current_page,omitempty"`
	Data        []*Oop `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *MyLikeOopResult) Reset() {
	*x = MyLikeOopResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyLikeOopResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyLikeOopResult) ProtoMessage() {}

func (x *MyLikeOopResult) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyLikeOopResult.ProtoReflect.Descriptor instead.
func (*MyLikeOopResult) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{12}
}

func (x *MyLikeOopResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MyLikeOopResult) GetShowNumber() int64 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

func (x *MyLikeOopResult) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *MyLikeOopResult) GetData() []*Oop {
	if x != nil {
		return x.Data
	}
	return nil
}

type LikeDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Star  int64 `protobuf:"varint,1,opt,name=star,proto3" json:"star,omitempty"`
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *LikeDetail) Reset() {
	*x = LikeDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oop_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeDetail) ProtoMessage() {}

func (x *LikeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_oop_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeDetail.ProtoReflect.Descriptor instead.
func (*LikeDetail) Descriptor() ([]byte, []int) {
	return file_oop_proto_rawDescGZIP(), []int{13}
}

func (x *LikeDetail) GetStar() int64 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *LikeDetail) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_oop_proto protoreflect.FileDescriptor

var file_oop_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6f, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f, 0x6f, 0x70,
	0x22, 0x3d, 0x0a, 0x09, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4f, 0x6f, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xf1, 0x02, 0x0a, 0x03, 0x4f, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12,
	0x31, 0x0a, 0x0b, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0b, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x33, 0x0a, 0x0c, 0x6d, 0x79, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4c,
	0x69, 0x6b, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x6d, 0x79, 0x5f, 0x6c, 0x69,
	0x6b, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x74, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6f, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73,
	0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6f, 0x6f, 0x70,
	0x2e, 0x4f, 0x6f, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x97, 0x01, 0x0a, 0x05, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x66,
	0x5f, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66,
	0x5f, 0x75, 0x69, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4f,
	0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x75,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x75,
	0x69, 0x64, 0x22, 0x60, 0x0a, 0x04, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74,
	0x61, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0d, 0x4c, 0x69, 0x6b, 0x65, 0x4f, 0x6f, 0x70, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x30, 0x0a, 0x0a, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x10, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x5e, 0x0a, 0x06, 0x4d, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x4d, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x4f, 0x6f,
	0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a,
	0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4f, 0x6f, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x36, 0x0a, 0x0a, 0x4c, 0x69, 0x6b, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74, 0x61,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xe6, 0x03, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x4f, 0x6f, 0x70, 0x12, 0x26, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4f,
	0x6f, 0x70, 0x12, 0x08, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4f, 0x6f, 0x70, 0x1a, 0x0e, 0x2e, 0x6f,
	0x6f, 0x70, 0x2e, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x27,
	0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x6f, 0x70, 0x12, 0x08, 0x2e, 0x6f, 0x6f,
	0x70, 0x2e, 0x4f, 0x6f, 0x70, 0x1a, 0x0e, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4f, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x6f, 0x70, 0x12, 0x0b, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x1a, 0x11, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x4f, 0x6f, 0x70, 0x12, 0x0a, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x1a, 0x0f, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f,
	0x74, 0x68, 0x65, 0x72, 0x4f, 0x6f, 0x70, 0x12, 0x0a, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x1a, 0x0f, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x09, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65,
	0x4f, 0x6f, 0x70, 0x12, 0x0a, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a,
	0x0f, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4d, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x12, 0x33, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x4f, 0x6f, 0x70, 0x12, 0x0e, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x4f, 0x6f, 0x70, 0x1a, 0x0f, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4d, 0x61, 0x6e, 0x79, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x07, 0x4c, 0x69, 0x6b, 0x65, 0x4f,
	0x6f, 0x70, 0x12, 0x09, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x1a, 0x12, 0x2e,
	0x6f, 0x6f, 0x70, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x4f, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x09, 0x4d, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x4f, 0x6f, 0x70,
	0x12, 0x0b, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x4d, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x1a, 0x14, 0x2e,
	0x6f, 0x6f, 0x70, 0x2e, 0x4d, 0x79, 0x4c, 0x69, 0x6b, 0x65, 0x4f, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c,
	0x69, 0x6b, 0x65, 0x4f, 0x6f, 0x70, 0x12, 0x0f, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x1a, 0x15, 0x2e, 0x6f, 0x6f, 0x70, 0x2e, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x6f, 0x70, 0x3b,
	0x6f, 0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oop_proto_rawDescOnce sync.Once
	file_oop_proto_rawDescData = file_oop_proto_rawDesc
)

func file_oop_proto_rawDescGZIP() []byte {
	file_oop_proto_rawDescOnce.Do(func() {
		file_oop_proto_rawDescData = protoimpl.X.CompressGZIP(file_oop_proto_rawDescData)
	})
	return file_oop_proto_rawDescData
}

var file_oop_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_oop_proto_goTypes = []interface{}{
	(*OneResult)(nil),        // 0: oop.OneResult
	(*Oop)(nil),              // 1: oop.Oop
	(*DeleteResult)(nil),     // 2: oop.DeleteResult
	(*Delete)(nil),           // 3: oop.Delete
	(*ManyResult)(nil),       // 4: oop.ManyResult
	(*Query)(nil),            // 5: oop.Query
	(*FollowOop)(nil),        // 6: oop.FollowOop
	(*Like)(nil),             // 7: oop.Like
	(*LikeOopResult)(nil),    // 8: oop.LikeOopResult
	(*CancelLike)(nil),       // 9: oop.CancelLike
	(*CancelLikeResult)(nil), // 10: oop.CancelLikeResult
	(*MyLike)(nil),           // 11: oop.MyLike
	(*MyLikeOopResult)(nil),  // 12: oop.MyLikeOopResult
	(*LikeDetail)(nil),       // 13: oop.LikeDetail
}
var file_oop_proto_depIdxs = []int32{
	1,  // 0: oop.OneResult.data:type_name -> oop.Oop
	13, // 1: oop.Oop.like_detail:type_name -> oop.LikeDetail
	13, // 2: oop.Oop.my_like_info:type_name -> oop.LikeDetail
	1,  // 3: oop.ManyResult.data:type_name -> oop.Oop
	1,  // 4: oop.MyLikeOopResult.data:type_name -> oop.Oop
	1,  // 5: oop.OperateOop.StoreOop:input_type -> oop.Oop
	1,  // 6: oop.OperateOop.UpdateOop:input_type -> oop.Oop
	3,  // 7: oop.OperateOop.DeleteOop:input_type -> oop.Delete
	5,  // 8: oop.OperateOop.QueryOwnerOop:input_type -> oop.Query
	5,  // 9: oop.OperateOop.QueryOtherOop:input_type -> oop.Query
	5,  // 10: oop.OperateOop.SquareOop:input_type -> oop.Query
	6,  // 11: oop.OperateOop.QueryFollowOop:input_type -> oop.FollowOop
	7,  // 12: oop.OperateOop.LikeOop:input_type -> oop.Like
	11, // 13: oop.OperateOop.MyLikeOop:input_type -> oop.MyLike
	9,  // 14: oop.OperateOop.CancelLikeOop:input_type -> oop.CancelLike
	0,  // 15: oop.OperateOop.StoreOop:output_type -> oop.OneResult
	0,  // 16: oop.OperateOop.UpdateOop:output_type -> oop.OneResult
	2,  // 17: oop.OperateOop.DeleteOop:output_type -> oop.DeleteResult
	4,  // 18: oop.OperateOop.QueryOwnerOop:output_type -> oop.ManyResult
	4,  // 19: oop.OperateOop.QueryOtherOop:output_type -> oop.ManyResult
	4,  // 20: oop.OperateOop.SquareOop:output_type -> oop.ManyResult
	4,  // 21: oop.OperateOop.QueryFollowOop:output_type -> oop.ManyResult
	8,  // 22: oop.OperateOop.LikeOop:output_type -> oop.LikeOopResult
	12, // 23: oop.OperateOop.MyLikeOop:output_type -> oop.MyLikeOopResult
	10, // 24: oop.OperateOop.CancelLikeOop:output_type -> oop.CancelLikeResult
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_oop_proto_init() }
func file_oop_proto_init() {
	if File_oop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowOop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Like); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeOopResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelLike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelLikeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyLike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyLikeOopResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oop_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oop_proto_goTypes,
		DependencyIndexes: file_oop_proto_depIdxs,
		MessageInfos:      file_oop_proto_msgTypes,
	}.Build()
	File_oop_proto = out.File
	file_oop_proto_rawDesc = nil
	file_oop_proto_goTypes = nil
	file_oop_proto_depIdxs = nil
}
