// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/userRegister/userRegister.proto

package pbUserRegister

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublickeyAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//存入mongodb与redis
	PbkAddr string `protobuf:"bytes,1,opt,name=pbkAddr,proto3" json:"pbkAddr,omitempty"`
}

func (x *PublickeyAddr) Reset() {
	*x = PublickeyAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userRegister_userRegister_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublickeyAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublickeyAddr) ProtoMessage() {}

func (x *PublickeyAddr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userRegister_userRegister_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublickeyAddr.ProtoReflect.Descriptor instead.
func (*PublickeyAddr) Descriptor() ([]byte, []int) {
	return file_proto_userRegister_userRegister_proto_rawDescGZIP(), []int{0}
}

func (x *PublickeyAddr) GetPbkAddr() string {
	if x != nil {
		return x.PbkAddr
	}
	return ""
}

type RandomCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//返回一个128位的随机码，并且存入redis
	RandomCode string `protobuf:"bytes,1,opt,name=randomCode,proto3" json:"randomCode,omitempty"`
}

func (x *RandomCode) Reset() {
	*x = RandomCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userRegister_userRegister_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomCode) ProtoMessage() {}

func (x *RandomCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userRegister_userRegister_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomCode.ProtoReflect.Descriptor instead.
func (*RandomCode) Descriptor() ([]byte, []int) {
	return file_proto_userRegister_userRegister_proto_rawDescGZIP(), []int{1}
}

func (x *RandomCode) GetRandomCode() string {
	if x != nil {
		return x.RandomCode
	}
	return ""
}

type EncryptedValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Sign      string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *EncryptedValue) Reset() {
	*x = EncryptedValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userRegister_userRegister_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedValue) ProtoMessage() {}

func (x *EncryptedValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userRegister_userRegister_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedValue.ProtoReflect.Descriptor instead.
func (*EncryptedValue) Descriptor() ([]byte, []int) {
	return file_proto_userRegister_userRegister_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptedValue) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *EncryptedValue) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid   string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_userRegister_userRegister_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userRegister_userRegister_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_userRegister_userRegister_proto_rawDescGZIP(), []int{3}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Token) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_proto_userRegister_userRegister_proto protoreflect.FileDescriptor

var file_proto_userRegister_userRegister_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b,
	0x65, 0x79, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x62, 0x6b, 0x41, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x62, 0x6b, 0x41, 0x64, 0x64, 0x72,
	0x22, 0x2c, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x42,
	0x0a, 0x0e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69,
	0x67, 0x6e, 0x22, 0x2f, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x32, 0xa0, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79,
	0x41, 0x64, 0x64, 0x72, 0x1a, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x00,
	0x12, 0x44, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a,
	0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x3b, 0x70,
	0x62, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_userRegister_userRegister_proto_rawDescOnce sync.Once
	file_proto_userRegister_userRegister_proto_rawDescData = file_proto_userRegister_userRegister_proto_rawDesc
)

func file_proto_userRegister_userRegister_proto_rawDescGZIP() []byte {
	file_proto_userRegister_userRegister_proto_rawDescOnce.Do(func() {
		file_proto_userRegister_userRegister_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_userRegister_userRegister_proto_rawDescData)
	})
	return file_proto_userRegister_userRegister_proto_rawDescData
}

var file_proto_userRegister_userRegister_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_userRegister_userRegister_proto_goTypes = []interface{}{
	(*PublickeyAddr)(nil),  // 0: userRegister.PublickeyAddr
	(*RandomCode)(nil),     // 1: userRegister.RandomCode
	(*EncryptedValue)(nil), // 2: userRegister.EncryptedValue
	(*Token)(nil),          // 3: userRegister.Token
}
var file_proto_userRegister_userRegister_proto_depIdxs = []int32{
	0, // 0: userRegister.UserRegister.GenerateMessage:input_type -> userRegister.PublickeyAddr
	2, // 1: userRegister.UserRegister.GenerateToken:input_type -> userRegister.EncryptedValue
	1, // 2: userRegister.UserRegister.GenerateMessage:output_type -> userRegister.RandomCode
	3, // 3: userRegister.UserRegister.GenerateToken:output_type -> userRegister.Token
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_userRegister_userRegister_proto_init() }
func file_proto_userRegister_userRegister_proto_init() {
	if File_proto_userRegister_userRegister_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_userRegister_userRegister_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublickeyAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userRegister_userRegister_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userRegister_userRegister_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptedValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_userRegister_userRegister_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_userRegister_userRegister_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userRegister_userRegister_proto_goTypes,
		DependencyIndexes: file_proto_userRegister_userRegister_proto_depIdxs,
		MessageInfos:      file_proto_userRegister_userRegister_proto_msgTypes,
	}.Build()
	File_proto_userRegister_userRegister_proto = out.File
	file_proto_userRegister_userRegister_proto_rawDesc = nil
	file_proto_userRegister_userRegister_proto_goTypes = nil
	file_proto_userRegister_userRegister_proto_depIdxs = nil
}
