// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/follower/follower.proto

package pbFollower

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Follower struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Following string `protobuf:"bytes,2,opt,name=following,proto3" json:"following,omitempty"`
}

func (x *Follower) Reset() {
	*x = Follower{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Follower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follower) ProtoMessage() {}

func (x *Follower) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follower.ProtoReflect.Descriptor instead.
func (*Follower) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{0}
}

func (x *Follower) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Follower) GetFollowing() string {
	if x != nil {
		return x.Following
	}
	return ""
}

type QFollowNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *QFollowNum) Reset() {
	*x = QFollowNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QFollowNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QFollowNum) ProtoMessage() {}

func (x *QFollowNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QFollowNum.ProtoReflect.Descriptor instead.
func (*QFollowNum) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{1}
}

func (x *QFollowNum) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type FollowNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Following string `protobuf:"bytes,2,opt,name=following,proto3" json:"following,omitempty"`
	Followed  string `protobuf:"bytes,3,opt,name=followed,proto3" json:"followed,omitempty"`
}

func (x *FollowNum) Reset() {
	*x = FollowNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowNum) ProtoMessage() {}

func (x *FollowNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowNum.ProtoReflect.Descriptor instead.
func (*FollowNum) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{2}
}

func (x *FollowNum) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FollowNum) GetFollowing() string {
	if x != nil {
		return x.Following
	}
	return ""
}

func (x *FollowNum) GetFollowed() string {
	if x != nil {
		return x.Followed
	}
	return ""
}

type OopFollowListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *OopFollowListReq) Reset() {
	*x = OopFollowListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OopFollowListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OopFollowListReq) ProtoMessage() {}

func (x *OopFollowListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OopFollowListReq.ProtoReflect.Descriptor instead.
func (*OopFollowListReq) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{3}
}

func (x *OopFollowListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *OopFollowListReq) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type OopFollowListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Uid  []string `protobuf:"bytes,2,rep,name=uid,proto3" json:"uid,omitempty"`
}

func (x *OopFollowListResp) Reset() {
	*x = OopFollowListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OopFollowListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OopFollowListResp) ProtoMessage() {}

func (x *OopFollowListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OopFollowListResp.ProtoReflect.Descriptor instead.
func (*OopFollowListResp) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{4}
}

func (x *OopFollowListResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OopFollowListResp) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

type Oop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid          string `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Uid          string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content      string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime   string `protobuf:"bytes,4,opt,name=create_time,proto3" json:"create_time,omitempty"`
	ShardTimes   int32  `protobuf:"varint,5,opt,name=shard_times,proto3" json:"shard_times,omitempty"`
	CommentTimes int32  `protobuf:"varint,6,opt,name=comment_times,proto3" json:"comment_times,omitempty"`
	LikeTimes    int32  `protobuf:"varint,7,opt,name=like_times,proto3" json:"like_times,omitempty"`
}

func (x *Oop) Reset() {
	*x = Oop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oop) ProtoMessage() {}

func (x *Oop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oop.ProtoReflect.Descriptor instead.
func (*Oop) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{5}
}

func (x *Oop) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *Oop) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Oop) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Oop) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Oop) GetShardTimes() int32 {
	if x != nil {
		return x.ShardTimes
	}
	return 0
}

func (x *Oop) GetCommentTimes() int32 {
	if x != nil {
		return x.CommentTimes
	}
	return 0
}

func (x *Oop) GetLikeTimes() int32 {
	if x != nil {
		return x.LikeTimes
	}
	return 0
}

type FollowListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Timestamp  string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ShowNumber int64  `protobuf:"varint,3,opt,name=show_number,proto3" json:"show_number,omitempty"`
	PageNumber int64  `protobuf:"varint,4,opt,name=page_number,proto3" json:"page_number,omitempty"`
}

func (x *FollowListReq) Reset() {
	*x = FollowListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListReq) ProtoMessage() {}

func (x *FollowListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListReq.ProtoReflect.Descriptor instead.
func (*FollowListReq) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{6}
}

func (x *FollowListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FollowListReq) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FollowListReq) GetShowNumber() int64 {
	if x != nil {
		return x.ShowNumber
	}
	return 0
}

func (x *FollowListReq) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type FollowListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Uid  []string `protobuf:"bytes,2,rep,name=uid,proto3" json:"uid,omitempty"`
}

func (x *FollowListResp) Reset() {
	*x = FollowListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListResp) ProtoMessage() {}

func (x *FollowListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListResp.ProtoReflect.Descriptor instead.
func (*FollowListResp) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{7}
}

func (x *FollowListResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FollowListResp) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

type RelationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Relationship []string `protobuf:"bytes,2,rep,name=relationship,proto3" json:"relationship,omitempty"`
}

func (x *RelationReq) Reset() {
	*x = RelationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationReq) ProtoMessage() {}

func (x *RelationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationReq.ProtoReflect.Descriptor instead.
func (*RelationReq) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{8}
}

func (x *RelationReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RelationReq) GetRelationship() []string {
	if x != nil {
		return x.Relationship
	}
	return nil
}

type RelationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Uid  []string `protobuf:"bytes,2,rep,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RelationResp) Reset() {
	*x = RelationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationResp) ProtoMessage() {}

func (x *RelationResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationResp.ProtoReflect.Descriptor instead.
func (*RelationResp) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{9}
}

func (x *RelationResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RelationResp) GetUid() []string {
	if x != nil {
		return x.Uid
	}
	return nil
}

var File_proto_follower_follower_proto protoreflect.FileDescriptor

var file_proto_follower_follower_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x08, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x69, 0x6e, 0x67, 0x22, 0x1e, 0x0a, 0x0a, 0x51, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x4e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x09, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4e,
	0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69,
	0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x22, 0x42,
	0x0a, 0x10, 0x4f, 0x6f, 0x70, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x39, 0x0a, 0x11, 0x4f, 0x6f, 0x70, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xcd, 0x01,
	0x0a, 0x03, 0x4f, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x83, 0x01,
	0x0a, 0x0d, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x0e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0b, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x22, 0x34, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x32, 0xe9, 0x03, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x33, 0x0a, 0x06, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x12, 0x12, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4e, 0x75, 0x6d, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x0b, 0x43, 0x61, 0x6e, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x2e, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x1a, 0x13, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x4e, 0x75, 0x6d, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1a, 0x2e,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x4f, 0x6f, 0x70, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x2e, 0x4f, 0x6f, 0x70, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17,
	0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x0e, 0x57, 0x68, 0x6f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x12,
	0x15, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x0d, 0x57, 0x68, 0x6f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x4d,
	0x65, 0x12, 0x15, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x3b, 0x70, 0x62, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_follower_follower_proto_rawDescOnce sync.Once
	file_proto_follower_follower_proto_rawDescData = file_proto_follower_follower_proto_rawDesc
)

func file_proto_follower_follower_proto_rawDescGZIP() []byte {
	file_proto_follower_follower_proto_rawDescOnce.Do(func() {
		file_proto_follower_follower_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_follower_follower_proto_rawDescData)
	})
	return file_proto_follower_follower_proto_rawDescData
}

var file_proto_follower_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_follower_follower_proto_goTypes = []interface{}{
	(*Follower)(nil),          // 0: follower.Follower
	(*QFollowNum)(nil),        // 1: follower.QFollowNum
	(*FollowNum)(nil),         // 2: follower.FollowNum
	(*OopFollowListReq)(nil),  // 3: follower.OopFollowListReq
	(*OopFollowListResp)(nil), // 4: follower.OopFollowListResp
	(*Oop)(nil),               // 5: follower.Oop
	(*FollowListReq)(nil),     // 6: follower.FollowListReq
	(*FollowListResp)(nil),    // 7: follower.FollowListResp
	(*RelationReq)(nil),       // 8: follower.RelationReq
	(*RelationResp)(nil),      // 9: follower.RelationResp
}
var file_proto_follower_follower_proto_depIdxs = []int32{
	0, // 0: follower.OperateFollow.Follow:input_type -> follower.Follower
	0, // 1: follower.OperateFollow.CanalFollow:input_type -> follower.Follower
	3, // 2: follower.OperateFollow.QueryFollowListAll:input_type -> follower.OopFollowListReq
	6, // 3: follower.OperateFollow.QueryFollowingList:input_type -> follower.FollowListReq
	6, // 4: follower.OperateFollow.QueryFollowedList:input_type -> follower.FollowListReq
	8, // 5: follower.OperateFollow.WhoFollowingMe:input_type -> follower.RelationReq
	8, // 6: follower.OperateFollow.WhoFollowedMe:input_type -> follower.RelationReq
	2, // 7: follower.OperateFollow.Follow:output_type -> follower.FollowNum
	2, // 8: follower.OperateFollow.CanalFollow:output_type -> follower.FollowNum
	4, // 9: follower.OperateFollow.QueryFollowListAll:output_type -> follower.OopFollowListResp
	7, // 10: follower.OperateFollow.QueryFollowingList:output_type -> follower.FollowListResp
	7, // 11: follower.OperateFollow.QueryFollowedList:output_type -> follower.FollowListResp
	9, // 12: follower.OperateFollow.WhoFollowingMe:output_type -> follower.RelationResp
	9, // 13: follower.OperateFollow.WhoFollowedMe:output_type -> follower.RelationResp
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_follower_follower_proto_init() }
func file_proto_follower_follower_proto_init() {
	if File_proto_follower_follower_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_follower_follower_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Follower); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QFollowNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OopFollowListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OopFollowListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_follower_follower_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_follower_follower_proto_goTypes,
		DependencyIndexes: file_proto_follower_follower_proto_depIdxs,
		MessageInfos:      file_proto_follower_follower_proto_msgTypes,
	}.Build()
	File_proto_follower_follower_proto = out.File
	file_proto_follower_follower_proto_rawDesc = nil
	file_proto_follower_follower_proto_goTypes = nil
	file_proto_follower_follower_proto_depIdxs = nil
}
